baseURL = 'https://plume.github.io/'
languageCode = 'en-us'
title = 'Plume blog'
subtitle = 'Focusing on the research of computer science and technology.'
theme = 'newtheme'
[params]
Author = "Gao Wei"
Email = "gggaaaooo@gmail.com" 
utteranc:
    enable: true
    repo: "plume/plume.github.io" 
    issueTerm: "title"
    theme: "github-light"  
